#!/usr/bin/env bash
#
# Prepare the local hosted peer runner for an iOS Simulator application, then
# start the hosted console. With no --app, this builds the TodoFixture.app used
# by Playtest's mobile tests.
#
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_FIXTURE="$REPO/tests/fixtures/todo-app-swiftui/build.sh"
GENERATED_MARKER="# Generated by scripts/hosted-ios.sh — rerun the script to replace this file."

usage() {
  sed -n 's/^# \{0,1\}//p' <<'USAGE'
# Usage:
#   scripts/hosted-ios.sh <project-key> [options]
#
# Example:
#   scripts/hosted-ios.sh hbnb
#
# This configures the site-scoped peer runner that `npm run hosted` already
# starts. The application and environment must already exist in the console as:
#   surface Mobile, platform iOS, application key "todo", environment key "local".
#
# Options:
#   --application <key>   Application key (default: todo)
#   --environment <key>   Environment key (default: local)
#   --app <path>          Existing unzipped .app bundle; otherwise build TodoFixture.app
#   --device <name>       Available iOS Simulator (default: iPhone 16)
#   --data-dir <path>     Hosted data root (default: .playtest-data)
#   --install-driver      Install Appium's xcuitest driver if it is missing
#   --no-boot             Do not boot the selected simulator
#   --configure-only      Write and validate runner.yaml, but do not start hosted
#   --replace             Replace a hand-maintained runner.yaml (a backup is kept)
#   -h, --help            Show this help
USAGE
}

PROJECT=""
APPLICATION="todo"
ENVIRONMENT="local"
APP_PATH=""
DEVICE="iPhone 16"
DATA_DIR="$REPO/.playtest-data"
INSTALL_DRIVER=0
BOOT_SIMULATOR=1
START_HOSTED=1
REPLACE=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --application)
      [ "$#" -ge 2 ] || { echo "hosted-ios: --application needs a key" >&2; exit 2; }
      APPLICATION="$2"
      shift 2
      ;;
    --environment)
      [ "$#" -ge 2 ] || { echo "hosted-ios: --environment needs a key" >&2; exit 2; }
      ENVIRONMENT="$2"
      shift 2
      ;;
    --app)
      [ "$#" -ge 2 ] || { echo "hosted-ios: --app needs a path" >&2; exit 2; }
      APP_PATH="$2"
      shift 2
      ;;
    --device)
      [ "$#" -ge 2 ] || { echo "hosted-ios: --device needs a simulator name" >&2; exit 2; }
      DEVICE="$2"
      shift 2
      ;;
    --data-dir)
      [ "$#" -ge 2 ] || { echo "hosted-ios: --data-dir needs a path" >&2; exit 2; }
      DATA_DIR="$2"
      shift 2
      ;;
    --install-driver)
      INSTALL_DRIVER=1
      shift
      ;;
    --no-boot)
      BOOT_SIMULATOR=0
      shift
      ;;
    --configure-only)
      START_HOSTED=0
      shift
      ;;
    --replace)
      REPLACE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "hosted-ios: unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
    *)
      if [ -n "$PROJECT" ]; then
        echo "hosted-ios: expected one project key, found both \"$PROJECT\" and \"$1\"" >&2
        exit 2
      fi
      PROJECT="$1"
      shift
      ;;
  esac
done

if [ -z "$PROJECT" ]; then
  echo "hosted-ios: give the project key shown in Settings, for example: scripts/hosted-ios.sh hbnb" >&2
  exit 2
fi

for pair in "project:$PROJECT" "application:$APPLICATION" "environment:$ENVIRONMENT"; do
  label="${pair%%:*}"
  key="${pair#*:}"
  if ! [[ "$key" =~ ^[a-z0-9][a-z0-9-]{0,62}$ ]]; then
    echo "hosted-ios: the $label key \"$key\" must use lowercase letters, digits and hyphens" >&2
    exit 2
  fi
done

if ! command -v xcrun >/dev/null 2>&1 || ! xcrun --find simctl >/dev/null 2>&1; then
  echo "hosted-ios: Xcode with an iOS Simulator SDK is required; install Xcode and run it once" >&2
  exit 2
fi

if [ -z "$APP_PATH" ]; then
  echo "hosted-ios: building TodoFixture.app…" >&2
  APP_PATH="$("$DEFAULT_FIXTURE" | tail -1)"
fi

APP_PATH="${APP_PATH%/}"
if [ ! -d "$APP_PATH" ]; then
  echo "hosted-ios: \"$APP_PATH\" is not an .app directory — unzip the build and pass the bundle itself" >&2
  exit 2
fi
if [[ "$APP_PATH" != *.app ]] || [ ! -f "$APP_PATH/Info.plist" ]; then
  echo "hosted-ios: \"$APP_PATH\" is not an iOS .app bundle (expected a .app directory containing Info.plist)" >&2
  exit 2
fi
APP_PATH="$(cd "$(dirname "$APP_PATH")" && pwd -P)/$(basename "$APP_PATH")"

APPIUM_BIN="$REPO/node_modules/.bin/appium"
if [ ! -x "$APPIUM_BIN" ]; then
  echo "hosted-ios: Appium is not installed in this checkout — run npm install" >&2
  exit 2
fi
APPIUM_HOME_DIR="${APPIUM_HOME:-$HOME/.appium}"

has_xcuitest() {
  APPIUM_HOME="$APPIUM_HOME_DIR" "$APPIUM_BIN" driver list --installed --json 2>/dev/null |
    node -e '
      let raw = "";
      process.stdin.setEncoding("utf8");
      process.stdin.on("data", chunk => raw += chunk);
      process.stdin.on("end", () => {
        try { process.exit(JSON.parse(raw).xcuitest ? 0 : 1); }
        catch { process.exit(1); }
      });
    '
}

if ! has_xcuitest; then
  if [ "$INSTALL_DRIVER" -eq 0 ]; then
    echo "hosted-ios: Appium's xcuitest driver is missing. Install it once with:" >&2
    echo "  APPIUM_HOME=\"$APPIUM_HOME_DIR\" \"$APPIUM_BIN\" driver install xcuitest" >&2
    echo "or rerun this command with --install-driver." >&2
    exit 2
  fi
  echo "hosted-ios: installing Appium's xcuitest driver…" >&2
  APPIUM_HOME="$APPIUM_HOME_DIR" "$APPIUM_BIN" driver install xcuitest
  has_xcuitest || { echo "hosted-ios: xcuitest was not available after installation" >&2; exit 2; }
fi

SIMULATORS="$(xcrun simctl list devices available --json)"
SIMULATOR_UDID="$(
  printf '%s' "$SIMULATORS" |
    node -e '
      const requested = process.argv[1];
      let raw = "";
      process.stdin.setEncoding("utf8");
      process.stdin.on("data", chunk => raw += chunk);
      process.stdin.on("end", () => {
        const devices = Object.values(JSON.parse(raw).devices || {}).flat();
        const matches = devices.filter(device => device.isAvailable !== false && device.name === requested);
        const selected = matches.find(device => device.state === "Booted") || matches[0];
        if (selected) process.stdout.write(selected.udid);
      });
    ' "$DEVICE"
)"
if [ -z "$SIMULATOR_UDID" ]; then
  echo "hosted-ios: no available simulator is named \"$DEVICE\". Choose one with --device from:" >&2
  printf '%s' "$SIMULATORS" |
    node -e '
      let raw = "";
      process.stdin.setEncoding("utf8");
      process.stdin.on("data", chunk => raw += chunk);
      process.stdin.on("end", () => {
        const devices = Object.values(JSON.parse(raw).devices || {}).flat();
        const names = [...new Set(devices.filter(device => device.isAvailable !== false && /^iPhone/.test(device.name)).map(device => device.name))];
        for (const name of names) process.stderr.write(`  ${name}\n`);
      });
    '
  exit 2
fi

if [ "$BOOT_SIMULATOR" -eq 1 ]; then
  echo "hosted-ios: booting ${DEVICE}…" >&2
  xcrun simctl boot "$SIMULATOR_UDID" >/dev/null 2>&1 || true
  xcrun simctl bootstatus "$SIMULATOR_UDID" -b
fi

case "$DATA_DIR" in
  /*) ;;
  *) DATA_DIR="$REPO/$DATA_DIR" ;;
esac
mkdir -p "$DATA_DIR"
DATA_DIR="$(cd "$DATA_DIR" && pwd -P)"
CONFIG_FILE="$DATA_DIR/runner.yaml"

if [ -f "$CONFIG_FILE" ] &&
   grep -qvE '^[[:space:]]*(#|$)' "$CONFIG_FILE" &&
   ! grep -qFx "$GENERATED_MARKER" "$CONFIG_FILE"; then
  if [ "$REPLACE" -eq 0 ]; then
    echo "hosted-ios: $CONFIG_FILE already contains a hand-maintained configuration." >&2
    echo "Rerun with --replace to back it up and replace it." >&2
    exit 2
  fi
  BACKUP_FILE="$CONFIG_FILE.backup-$(date +%Y%m%d-%H%M%S)"
  cp "$CONFIG_FILE" "$BACKUP_FILE"
  echo "hosted-ios: backed up the previous runner config to $BACKUP_FILE" >&2
fi

yaml_quote() {
  node -p 'JSON.stringify(process.argv[1])' "$1"
}

PROJECT_YAML="$(yaml_quote "$PROJECT")"
APPLICATION_YAML="$(yaml_quote "$APPLICATION")"
ENVIRONMENT_YAML="$(yaml_quote "$ENVIRONMENT")"
APP_PATH_YAML="$(yaml_quote "$APP_PATH")"
DEVICE_YAML="$(yaml_quote "$DEVICE")"
TEMP_CONFIG="$(mktemp "$DATA_DIR/.runner.yaml.XXXXXX")"
trap 'rm -f "$TEMP_CONFIG"' EXIT

{
  echo "$GENERATED_MARKER"
  echo "version: 1"
  echo
  echo "targets:"
  echo "  - project: $PROJECT_YAML"
  echo "    application: $APPLICATION_YAML"
  echo "    environment: $ENVIRONMENT_YAML"
  echo "    platform: ios"
  echo "    app: $APP_PATH_YAML"
  echo "    backend: local-ios"
  echo "    device: $DEVICE_YAML"
  echo
  echo "mobile:"
  echo "  backends:"
  echo "    local-ios:"
  echo "      platform: ios"
  echo "      appium:"
  echo "        mode: managed"
} > "$TEMP_CONFIG"

node --input-type=module -e '
  import { loadRunnerConfig } from "./packages/platform/runner-agent/src/runner-config.ts";
  loadRunnerConfig(process.argv[1]);
' "$TEMP_CONFIG"

chmod 600 "$TEMP_CONFIG"
mv "$TEMP_CONFIG" "$CONFIG_FILE"
trap - EXIT

echo >&2
echo "  iOS runner ready" >&2
echo "  target        $PROJECT/$APPLICATION/$ENVIRONMENT" >&2
echo "  app           $APP_PATH" >&2
echo "  simulator     $DEVICE" >&2
echo "  runner config $CONFIG_FILE" >&2
echo >&2

if [ "$START_HOSTED" -eq 0 ]; then
  echo "Restart npm run hosted so its peer runner reloads this configuration." >&2
  exit 0
fi

echo "hosted-ios: starting the console and its configured peer runner…" >&2
exec env PLAYTEST_DATA_DIR="$DATA_DIR" APPIUM_HOME="$APPIUM_HOME_DIR" bash "$REPO/scripts/hosted-server.sh"
