// Seeded desk state. Everything here is literal: no value is derived at load
// time, so `POST /__reset` restores an exact, byte-stable starting state and
// the business rules can be checked against the seeds independently.

export const DEPARTMENTS = [
  "Architecture",
  "Athletics",
  "Design",
  "Film & Media",
  "Journalism",
  "Music",
  "Student Life",
];

export const CATEGORIES = ["Audio", "Cameras", "Computing", "Lighting", "Support"];

export const EQUIPMENT = [
  {
    id: "cam-c70",
    tag: "CAM-C70",
    name: "Canon C70 Cinema Camera",
    category: "Cameras",
    description:
      "Super 35 cinema body with dual-gain output, built-in ND filters and an RF 24-105mm zoom. Ships in a hard case with two batteries and a 512GB card.",
    specs: [
      { label: "Sensor", value: "Super 35 DGO" },
      { label: "Mount", value: "Canon RF" },
      { label: "Media", value: "2x SD UHS-II" },
      { label: "Case weight", value: "7.4 kg" },
    ],
    totalUnits: 3,
    dailyRateCents: 1800,
    replacementValueCents: 540000,
  },
  {
    id: "cam-a7iv",
    tag: "CAM-A74",
    name: "Sony A7 IV Mirrorless Kit",
    category: "Cameras",
    description:
      "Full-frame hybrid body for interviews and stills, supplied with a 24-70mm f/2.8, three batteries and a dual charger.",
    specs: [
      { label: "Sensor", value: "33MP full frame" },
      { label: "Mount", value: "Sony E" },
      { label: "Media", value: "CFexpress A / SD" },
      { label: "Case weight", value: "3.1 kg" },
    ],
    totalUnits: 4,
    dailyRateCents: 1200,
    replacementValueCents: 290000,
  },
  {
    id: "cam-gopro",
    tag: "CAM-GP12",
    name: "GoPro Hero 12 Action Kit",
    category: "Cameras",
    description:
      "Waterproof action camera with helmet, chest and suction mounts. Popular for match-day and fieldwork coverage.",
    specs: [
      { label: "Max capture", value: "5.3K60" },
      { label: "Waterproof", value: "10 m" },
      { label: "Media", value: "microSD 256GB" },
      { label: "Case weight", value: "0.9 kg" },
    ],
    totalUnits: 6,
    dailyRateCents: 600,
    replacementValueCents: 48000,
  },
  {
    id: "aud-h6",
    tag: "AUD-H6",
    name: "Zoom H6 Field Recorder",
    category: "Audio",
    description:
      "Six-track portable recorder with interchangeable capsules, XLR inputs and a windshield. The desk's default choice for radio packages.",
    specs: [
      { label: "Tracks", value: "6" },
      { label: "Inputs", value: "4x XLR/TRS" },
      { label: "Media", value: "SD 128GB" },
      { label: "Case weight", value: "1.2 kg" },
    ],
    totalUnits: 5,
    dailyRateCents: 500,
    replacementValueCents: 42000,
  },
  {
    id: "aud-lav",
    tag: "AUD-WGO2",
    name: "Rode Wireless GO II Lav Pair",
    category: "Audio",
    description:
      "Two-channel wireless lavalier set with on-board backup recording, lapel clips and windshields.",
    specs: [
      { label: "Channels", value: "2" },
      { label: "Range", value: "200 m line of sight" },
      { label: "Battery", value: "7 hours" },
      { label: "Case weight", value: "0.5 kg" },
    ],
    totalUnits: 8,
    dailyRateCents: 400,
    replacementValueCents: 36000,
  },
  {
    id: "aud-boom",
    tag: "AUD-416",
    name: "Sennheiser MKH-416 Boom Kit",
    category: "Audio",
    description:
      "Shotgun microphone, blimp, softie and a carbon boom pole. Booked out heavily during documentary term.",
    specs: [
      { label: "Pattern", value: "Supercardioid" },
      { label: "Pole", value: "3 m carbon" },
      { label: "Power", value: "48V phantom" },
      { label: "Case weight", value: "2.8 kg" },
    ],
    totalUnits: 2,
    dailyRateCents: 900,
    replacementValueCents: 145000,
  },
  {
    id: "lig-aputure",
    tag: "LIG-300X",
    name: "Aputure 300x LED Light",
    category: "Lighting",
    description:
      "Bi-colour 300W COB fixture with Bowens mount, reflector and a road case. Needs a mains outlet within 5 m.",
    specs: [
      { label: "Output", value: "300 W bi-colour" },
      { label: "Colour", value: "2700-6500 K" },
      { label: "Mount", value: "Bowens" },
      { label: "Case weight", value: "12.6 kg" },
    ],
    totalUnits: 4,
    dailyRateCents: 1100,
    replacementValueCents: 129000,
  },
  {
    id: "lig-softbox",
    tag: "LIG-LAN",
    name: "Lantern Softbox Kit",
    category: "Lighting",
    description:
      "Collapsible 90cm lantern with skirt and speed ring, plus a weighted C-stand. Pairs with any Bowens-mount fixture.",
    specs: [
      { label: "Diameter", value: "90 cm" },
      { label: "Mount", value: "Bowens" },
      { label: "Stand", value: "C-stand, 3 m" },
      { label: "Case weight", value: "6.0 kg" },
    ],
    totalUnits: 3,
    dailyRateCents: 300,
    replacementValueCents: 26000,
  },
  {
    id: "sup-tripod",
    tag: "SUP-504X",
    name: "Manfrotto 504X Tripod",
    category: "Support",
    description:
      "Fluid-head video tripod with a 75mm bowl, mid-level spreader and a padded carry bag. Rated to 12 kg.",
    specs: [
      { label: "Head", value: "Fluid, 75 mm bowl" },
      { label: "Payload", value: "12 kg" },
      { label: "Max height", value: "1.68 m" },
      { label: "Case weight", value: "5.2 kg" },
    ],
    totalUnits: 6,
    dailyRateCents: 400,
    replacementValueCents: 54000,
  },
  {
    id: "sup-gimbal",
    tag: "SUP-RS4",
    name: "DJI RS 4 Pro Gimbal",
    category: "Support",
    description:
      "Three-axis stabiliser for bodies up to 4.5 kg, with focus motor, briefcase handle and a fitted case.",
    specs: [
      { label: "Payload", value: "4.5 kg" },
      { label: "Battery", value: "12 hours" },
      { label: "Extras", value: "Focus motor" },
      { label: "Case weight", value: "4.4 kg" },
    ],
    totalUnits: 2,
    dailyRateCents: 1000,
    replacementValueCents: 102000,
  },
  {
    id: "com-mbp",
    tag: "COM-MBP16",
    name: 'MacBook Pro 16" Edit Laptop',
    category: "Computing",
    description:
      "Edit-suite laptop preloaded with the media licences, supplied with a 140W charger and a padded sleeve.",
    specs: [
      { label: "Memory", value: "48 GB" },
      { label: "Storage", value: "2 TB" },
      { label: "Ports", value: "3x Thunderbolt, HDMI, SD" },
      { label: "Case weight", value: "2.9 kg" },
    ],
    totalUnits: 3,
    dailyRateCents: 1500,
    replacementValueCents: 360000,
  },
  {
    id: "com-drive",
    tag: "COM-T9",
    name: "Samsung T9 4TB SSD",
    category: "Computing",
    description:
      "Rugged bus-powered SSD for rushes, formatted exFAT with both USB-C cables in the pouch.",
    specs: [
      { label: "Capacity", value: "4 TB" },
      { label: "Interface", value: "USB 3.2 Gen 2x2" },
      { label: "Format", value: "exFAT" },
      { label: "Case weight", value: "0.2 kg" },
    ],
    totalUnits: 7,
    dailyRateCents: 200,
    replacementValueCents: 21000,
  },
];

export const LOANS = [
  {
    id: "L-1041",
    borrower: {
      name: "Priya Raman",
      email: "priya.raman@fairmont.edu",
      department: "Journalism",
    },
    purpose: "Election night interviews for the campus newsroom.",
    lines: [
      { equipmentId: "cam-a7iv", quantity: 1 },
      { equipmentId: "aud-lav", quantity: 1 },
    ],
    loanDays: 7,
    pickupDate: "2026-03-09",
    dueDate: "2026-03-16",
    status: "out",
    bookedAt: "2026-03-05T10:42:00Z",
    quote: {
      baseChargeCents: 11200,
      bundleDiscountCents: 0,
      depositCents: 29000,
      totalDueCents: 40200,
      unitCount: 2,
      replacementTotalCents: 326000,
    },
    approvalRequired: true,
    decision: {
      outcome: "approved",
      decidedAt: "2026-03-06T09:10:00Z",
      decidedBy: "Rowan Ellis",
      reason: null,
    },
    pickedUpAt: "2026-03-09T09:20:00Z",
    extensionsUsed: 0,
    returnedAt: null,
    condition: null,
    conditionNote: null,
    lateFeeCents: null,
    depositOutcome: null,
    cancelledAt: null,
  },
  {
    id: "L-1042",
    borrower: {
      name: "Marcus Webb",
      email: "marcus.webb@fairmont.edu",
      department: "Film & Media",
    },
    purpose: "Third-year thesis shoot, two exterior locations.",
    lines: [
      { equipmentId: "cam-c70", quantity: 1 },
      { equipmentId: "sup-tripod", quantity: 1 },
      { equipmentId: "lig-aputure", quantity: 1 },
    ],
    loanDays: 7,
    pickupDate: "2026-03-04",
    dueDate: "2026-03-11",
    status: "out",
    bookedAt: "2026-03-02T14:05:00Z",
    quote: {
      baseChargeCents: 23100,
      bundleDiscountCents: 2310,
      depositCents: 66900,
      totalDueCents: 87690,
      unitCount: 3,
      replacementTotalCents: 723000,
    },
    approvalRequired: true,
    decision: {
      outcome: "approved",
      decidedAt: "2026-03-03T08:55:00Z",
      decidedBy: "Rowan Ellis",
      reason: null,
    },
    pickedUpAt: "2026-03-04T10:00:00Z",
    extensionsUsed: 0,
    returnedAt: null,
    condition: null,
    conditionNote: null,
    lateFeeCents: null,
    depositOutcome: null,
    cancelledAt: null,
  },
  {
    id: "L-1043",
    borrower: {
      name: "Dana Okoye",
      email: "dana.okoye@fairmont.edu",
      department: "Athletics",
    },
    purpose: "Helmet-cam coverage of the inter-college relay.",
    lines: [{ equipmentId: "cam-gopro", quantity: 2 }],
    loanDays: 3,
    pickupDate: "2026-03-17",
    dueDate: "2026-03-20",
    status: "ready",
    bookedAt: "2026-03-13T10:05:00Z",
    quote: {
      baseChargeCents: 3600,
      bundleDiscountCents: 0,
      depositCents: 0,
      totalDueCents: 3600,
      unitCount: 2,
      replacementTotalCents: 96000,
    },
    approvalRequired: false,
    decision: null,
    pickedUpAt: null,
    extensionsUsed: 0,
    returnedAt: null,
    condition: null,
    conditionNote: null,
    lateFeeCents: null,
    depositOutcome: null,
    cancelledAt: null,
  },
  {
    id: "L-1044",
    borrower: {
      name: "Theo Lindqvist",
      email: "theo.lindqvist@fairmont.edu",
      department: "Music",
    },
    purpose: "Two-week residency recording in the chapel.",
    lines: [
      { equipmentId: "aud-boom", quantity: 1 },
      { equipmentId: "aud-h6", quantity: 1 },
    ],
    loanDays: 14,
    pickupDate: "2026-03-16",
    dueDate: "2026-03-30",
    status: "pending_approval",
    bookedAt: "2026-03-16T08:20:00Z",
    quote: {
      baseChargeCents: 19600,
      bundleDiscountCents: 0,
      depositCents: 14500,
      totalDueCents: 34100,
      unitCount: 2,
      replacementTotalCents: 187000,
    },
    approvalRequired: true,
    decision: null,
    pickedUpAt: null,
    extensionsUsed: 0,
    returnedAt: null,
    condition: null,
    conditionNote: null,
    lateFeeCents: null,
    depositOutcome: null,
    cancelledAt: null,
  },
  {
    id: "L-1045",
    borrower: {
      name: "Aisha Farouk",
      email: "aisha.farouk@fairmont.edu",
      department: "Architecture",
    },
    purpose: "Site survey film for the riverside studio project.",
    lines: [
      { equipmentId: "com-mbp", quantity: 1 },
      { equipmentId: "cam-c70", quantity: 1 },
    ],
    loanDays: 7,
    pickupDate: "2026-03-18",
    dueDate: "2026-03-25",
    status: "pending_approval",
    bookedAt: "2026-03-13T15:40:00Z",
    quote: {
      baseChargeCents: 23100,
      bundleDiscountCents: 0,
      depositCents: 90000,
      totalDueCents: 113100,
      unitCount: 2,
      replacementTotalCents: 900000,
    },
    approvalRequired: true,
    decision: null,
    pickedUpAt: null,
    extensionsUsed: 0,
    returnedAt: null,
    condition: null,
    conditionNote: null,
    lateFeeCents: null,
    depositOutcome: null,
    cancelledAt: null,
  },
  {
    id: "L-1046",
    borrower: {
      name: "Owen Castillo",
      email: "owen.castillo@fairmont.edu",
      department: "Journalism",
    },
    purpose: "Vox pops on the science quad.",
    lines: [{ equipmentId: "aud-h6", quantity: 1 }],
    loanDays: 3,
    pickupDate: "2026-03-02",
    dueDate: "2026-03-05",
    status: "returned",
    bookedAt: "2026-02-27T11:00:00Z",
    quote: {
      baseChargeCents: 1500,
      bundleDiscountCents: 0,
      depositCents: 0,
      totalDueCents: 1500,
      unitCount: 1,
      replacementTotalCents: 42000,
    },
    approvalRequired: false,
    decision: null,
    pickedUpAt: "2026-03-02T09:05:00Z",
    extensionsUsed: 0,
    returnedAt: "2026-03-05T14:20:00Z",
    condition: "good",
    conditionNote: null,
    lateFeeCents: 0,
    depositOutcome: "none",
    cancelledAt: null,
  },
  {
    id: "L-1047",
    borrower: {
      name: "Sofia Marchetti",
      email: "sofia.marchetti@fairmont.edu",
      department: "Film & Media",
    },
    purpose: "Portrait lighting workshop, cancelled by the tutor.",
    lines: [
      { equipmentId: "lig-softbox", quantity: 2 },
      { equipmentId: "sup-tripod", quantity: 1 },
    ],
    loanDays: 1,
    pickupDate: "2026-03-10",
    dueDate: "2026-03-11",
    status: "cancelled",
    bookedAt: "2026-03-09T09:15:00Z",
    quote: {
      baseChargeCents: 1000,
      bundleDiscountCents: 100,
      depositCents: 0,
      totalDueCents: 900,
      unitCount: 3,
      replacementTotalCents: 106000,
    },
    approvalRequired: false,
    decision: null,
    pickedUpAt: null,
    extensionsUsed: 0,
    returnedAt: null,
    condition: null,
    conditionNote: null,
    lateFeeCents: null,
    depositOutcome: null,
    cancelledAt: "2026-03-09T16:30:00Z",
  },
  {
    id: "L-1048",
    borrower: {
      name: "Nina Brandt",
      email: "nina.brandt@fairmont.edu",
      department: "Design",
    },
    purpose: "Moving-camera sequences for the degree show reel.",
    lines: [{ equipmentId: "sup-gimbal", quantity: 2 }],
    loanDays: 7,
    pickupDate: "2026-03-12",
    dueDate: "2026-03-19",
    status: "out",
    bookedAt: "2026-03-11T13:00:00Z",
    quote: {
      baseChargeCents: 14000,
      bundleDiscountCents: 0,
      depositCents: 20400,
      totalDueCents: 34400,
      unitCount: 2,
      replacementTotalCents: 204000,
    },
    approvalRequired: false,
    decision: null,
    pickedUpAt: "2026-03-12T09:30:00Z",
    extensionsUsed: 0,
    returnedAt: null,
    condition: null,
    conditionNote: null,
    lateFeeCents: null,
    depositOutcome: null,
    cancelledAt: null,
  },
];

export const NEXT_LOAN_NUMBER = 1049;

export const OPERATOR = { name: "Rowan Ellis", role: "Desk supervisor" };

/** A deep copy of the seeds, so callers can never mutate the frozen data. */
export function seedState() {
  return {
    equipment: structuredClone(EQUIPMENT),
    loans: structuredClone(LOANS),
    drafts: [],
    nextLoanNumber: NEXT_LOAN_NUMBER,
    nextDraftNumber: 1,
  };
}
